# Generated by Django 3.0.5 on 2023-12-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.TextField(max_length=50)),
                ('de_desc', models.TextField(max_length=200)),
            ],
        ),
    ]
