# Generated by Django 3.0.5 on 2023-12-13 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='de_desc',
            new_name='dep_desc',
        ),
    ]
